# Grammar information
ERG: /Users/lizcconrad/Documents/PhD/GP2/ERG_2023/erg-2023.dat
SEMI: /Users/lizcconrad/Documents/PhD/GP2/ERG_2023/trunk/etc/erg.smi
# Data locations
parent_data_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/synthesized